coverage:
  status:
    project:
      dsl:
        paths:
          - de.joneug.mdal
      ide:
        paths:
          - de.joneug.mdal.ide
      standalone:
        paths:
          - de.joneug.mdal.standalone
