name: Package

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
env:
  IMAGE_NAME: joneug/mdal
  IMAGE_TAG: latest
  
jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/checkout@v2
      - name: Create Dist
        run: ./gradlew distUnzip
      - name: Publish to Docker Hub
        if: runner.os != 'windows'
        run: |
          cd de.joneug.mdal.standalone
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u joneug --password-stdin
          docker build -t $IMAGE_NAME:$IMAGE_TAG-linux .
          docker push $IMAGE_NAME
      - name: Publish to Docker Hub
        if: runner.os == 'windows'
        run: |
          cd de.joneug.mdal.standalone
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u joneug --password-stdin
          docker build -f Dockerfile.windows -t "${env:IMAGE_NAME}:${env:IMAGE_TAG}-windows" .
          docker push "${env:IMAGE_NAME}"
  manifest:
    needs: [package]
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.2/manifest-tool-linux-amd64
          chmod +x manifest-tool
          ./manifest-tool --username joneug --password "${{ secrets.DOCKER_PASSWORD }}" push from-args \
            --platforms linux/amd64,windows/amd64 \
            --template $IMAGE_NAME:$IMAGE_TAG-OS \
            --target $IMAGE_NAME:$IMAGE_TAG
