name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        run: ./gradlew build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Set up Environment Variables (IDE)
        run: |
          echo "::set-env name=ASSET_PATH::$(ls de.joneug.mdal.ide/build/distributions/*.zip | head -1)"
          echo "::set-env name=ASSET_NAME::$(cd de.joneug.mdal.ide/build/distributions/ && ls *.zip | head -1)"
      - name: Upload Release Asset (IDE)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ASSET_PATH }}
          asset_name: ${{ env.ASSET_NAME }}
          asset_content_type: application/zip
      - name: Set up Environment Variables (CLI)
        run: |
          echo "::set-env name=ASSET_PATH::$(ls de.joneug.mdal.standalone/build/distributions/*.zip | head -1)"
          echo "::set-env name=ASSET_NAME::$(cd de.joneug.mdal.standalone/build/distributions/ && ls *.zip | head -1)"
      - name: Upload Release Asset (CLI)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ASSET_PATH }}
          asset_name: ${{ env.ASSET_NAME }}
          asset_content_type: application/zip
